### ISSUE TITLE
安装最新版本2019/8/23的，成功安装登陆后台报错

### ISSUE THREAD

**Issue by Arvingrep** [crmeb/CRMEB#10]
Type error: Too few arguments to function think\\Model::data(), 0 passed in /www/wwwroot/129.***.***.125/thinkphp/library/think/Model.php on line 620 and at least 1 expected
具体：和域名绑定一起用ip(默认端口80)么有正常显示，用域名登陆就会报上面的错

**Comment by thundersword** [comment]
遇到同样错误，去掉index中php版本限制之后，切换到php5.6版本，报错消失，其他功能是否正常有待验证

**Comment by sugar1569** [comment]
最低要求php7.1
