### ISSUE TITLE
3.0版本安装成功后登录后台提示数据库连接错误

### ISSUE THREAD

**Issue by sayid** [crmeb/CRMEB#11]
SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

同样环境安装2.6是没有问题的。
目前版本是3.0最新版本

**Comment by sugar1569** [comment]
看看根目录env文件配置是否没有权限，没有配置成功，可以手动修改一下配置

发自我的 iPhone

**Comment by sayid** [comment]
还是不行,我手动修改config/database.php之后就可以了

**Comment by sayid** [comment]
![image](https://user-images.githubusercontent.com/362920/65380745-962b1100-dd14-11e9-924f-beae249ae683.png)
现在前台显示空白的
