### ISSUE TITLE
请问没有runtime文件夹

### ISSUE THREAD

**Issue by jovinlee** [crmeb/CRMEB#13]
Warning: is_file(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/runtime) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/templates/step2.php on line 111

Warning: is_dir(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/runtime) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/templates/step2.php on line 112

Warning: is_dir(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/runtime) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/index.php on line 457

Warning: is_dir(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/runtime/) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/index.php on line 471

Warning: is_file(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/runtime) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/index.php on line 379

Warning: is_readable(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/runtime) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/templates/step2.php on line 125

Warning: is_file(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/.env) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/templates/step2.php on line 111

Warning: is_dir(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/.env) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/templates/step2.php on line 112

Warning: is_dir(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/.env) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/index.php on line 457

Warning: is_dir(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/.env/) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/index.php on line 471

Warning: is_file(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/.env) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/index.php on line 379

Warning: is_readable(): open_basedir restriction in effect. File(/www/wwwroot/c.upp188.top/CRMEB/.env) is not within the allowed path(s): (/www/wwwroot/c.upp188.top/CRMEB/public/:/tmp/:/proc/) in /www/wwwroot/c.upp188.top/CRMEB/public/install/templates/step2.php on line 125

**Comment by sugar1569** [comment]
根目录手动创建一个吧

发自我的 iPhone

**Comment by suchenrain** [comment]
自己在根目录创建一个，更改下目录权限就可以了
