### ISSUE TITLE
无法引用上级目录的文件啊

### ISSUE THREAD

**Issue by idersec** [crmeb/CRMEB#14]
Fatal error: require(): Failed opening required '/home/wwwroot/test.com/public/../vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /home/wwwroot/test.com/public/index.php on line 16
我看PHP文件写的：
require __DIR__ . '/../vendor/autoload.php';

**Comment by sugar1569** [comment]
站点目录配置没设置好吧
