### ISSUE TITLE
小程序配置没填错提示"获取session_key失败"

### ISSUE THREAD

**Issue by FengFeng-is-me** [crmeb/CRMEB#16]
![image](https://user-images.githubusercontent.com/32693877/70788224-621f3380-1dcb-11ea-9de8-ae8484d9f33f.png)
提示信息{"status":400,"msg":"获取session_key失败，请检查您的配置！","data":{"line":243,"message":"Request AccessToken fail. response: {\"errcode\":40013,\"errmsg\":\"invalid appid hint: [zr13ta0204e668]\"}"}}

**Comment by sugar1569** [comment]
错误就是没有配置好的，刷一下缓存试试

发自我的 iPhone

**Comment by xumengqiang** [comment]
php版本问题，应该是php版本太高了
