### ISSUE TITLE
ThinkPHP 5.0.x 远程代码执行高危漏洞

### ISSUE THREAD

**Issue by polichan** [crmeb/CRMEB#3]
漏洞存在范围：ThinkPHP < 5.0.24
漏洞存在文件：Request.php
建议尽快修复 :)

**Comment by sugar1569** [comment]
谢谢反馈------------------ 原始邮件 ------------------
发件人: "Hexwell"<notifications@github.com>
发送时间: 2019年7月7日(星期天) 晚上11:34
收件人: "crmeb/CRMEB"<CRMEB@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [crmeb/CRMEB] ThinkPHP 5.0.x 远程代码执行高危漏洞 (#3)



漏洞存在范围：ThinkPHP < 5.0.24
 漏洞存在文&#x4EF6;：Request.php
 建议尽快修复 :)
 
&mdash;
