### ISSUE TITLE
Several security vulnerabilities in the latest version

### ISSUE THREAD

**Issue by stArl23** [crmeb/CRMEB#41]
Several security vulnerabilities in the latest version, the details are put in https://www.star123.top/2021/12/17/Vulnerability-in-CRMEB/, the password of doucment is sent to admin@xazbkj.com.

**Comment by rootGH** [comment]
> Several security vulnerabilities in the latest version, the details are put in https://www.star123.top/2021/12/17/Vulnerability-in-CRMEB/, the password of doucment is sent to [admin@xazbkj.com](mailto:admin@xazbkj.com).

May I read your paper, could you send the password to [rootgh@139.com](mailto:rootgh@139.com), thanks!
