### ISSUE TITLE
订单管理出错

### ISSUE THREAD

**Issue by sonwa** [crmeb/CRMEB#8]
订单管理出错，我看你们那个在线演示那个站是正常的，请问是什么原因？

![image](https://user-images.githubusercontent.com/1425134/62788228-1137bf80-baf9-11e9-9a61-b4984995da51.png)

**Comment by sonwa** [comment]
评论管理都是

![image](https://user-images.githubusercontent.com/1425134/62788331-3d534080-baf9-11e9-9b5b-726d13e00da9.png)

**Comment by sugar1569** [comment]
js 没加载好吧

**Comment by sonwa** [comment]
git下来没改过啥直接运行的，当前以为mac系统问题换了linux环境下都是订单和理出错。
