### ISSUE TITLE
crmeb.sql执行文件有问题

### ISSUE THREAD

**Issue by GabbyMrH** [crmeb/CRMEB#84]
该文件有很多数据是有问题的，导入的时候各种报错，麻烦检查一遍并更新最新的。

**Comment by fengmangbl** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我不在电脑前，无法亲自回复您的邮件。我将尽快给您回复。

**Comment by pk2993635720** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
